Faker for user and post create
R1cro/SocialNetwork pull request #12
Opened 2016-10-14 15:32 UTC by R1cro

2016-10-18 15:52 UTC, barmidrol requested changes
Breakin' changes.

2016-10-18 15:52 UTC, barmidrol commented on app/controllers/microposts_controller.rb
🔪

2016-10-18 15:52 UTC, barmidrol commented on app/helpers/users_helper.rb
> +    # gravatar_url = get_avatar
🔪

2016-10-18 15:52 UTC, barmidrol commented on app/helpers/microposts_helper.rb
> +       link_to('#' + tag, tag_path(tag_id_by_name(tag)))
🔪

2016-10-18 15:52 UTC, barmidrol commented on db/seeds.rb
>      password:              "swseuz2U",
Я надеюсь это не тот пароль, который ты используешь на машине.

2016-10-18 15:52 UTC, barmidrol commented on db/seeds.rb
> +  content = '#' + tag_name + Faker::Lorem.sentence(13)
Халтура. Нужно, чтобы несколько **случайных** слов из предложения становились хэштэгами.

2016-10-18 15:52 UTC, barmidrol commented on db/seeds.rb
> +followers = users[15..30]
Опять же, где случайность? Нужно, чтобы **случайное** количество **случайных** юзеров фолловили друг друга.

2016-10-18 15:52 UTC, barmidrol commented on db/seeds.rb
> +  )
С индентацией проблемы.

2016-10-18 15:55 UTC, barmidrol commented
С нетерпением ждем третьей части! 😉 
![screenshot at oct 18 18-54-09](https://cloud.githubusercontent.com/assets/11842839/19485645/5581066e-9564-11e6-8fd0-42e248e879da.png)

2016-10-18 16:07 UTC, R1cro commented on db/seeds.rb
>      password:              "swseuz2U",
От старой банковской карточки. Но и от машины...60+ дней назад.

2016-10-18 16:08 UTC, R1cro commented on db/seeds.rb
> +  content = '#' + tag_name + Faker::Lorem.sentence(13)
Окей. Добавлю в таски.

2016-10-18 16:08 UTC, R1cro commented on db/seeds.rb
> +followers = users[15..30]
Рандомно? А есть ли в этом необходимость и что таким образом будет проверяться?

2016-10-18 16:10 UTC, barmidrol commented on db/seeds.rb
>      password:              "swseuz2U",
Не надо так.

2016-10-18 16:11 UTC, R1cro commented on db/seeds.rb
>      password:              "swseuz2U",
По привычке. Просто хорошо запомнился пасс.

2016-10-18 16:13 UTC, barmidrol commented on db/seeds.rb
> +followers = users[15..30]
По-хорошему, сгенерированные данные должны как можно точнее отображать реальное поведение реальных пользователей. А пользователи ведут себя более непредсказуемо, чем ты в своем коде описал. Плюс это будет нужно для следующей фичи.

2016-10-18 16:18 UTC, barmidrol commented on db/seeds.rb
>      password:              "swseuz2U",
Будь готов к тому, что этот пароль вместе с имэйлом уже кто-то получил.

2016-10-18 16:19 UTC, barmidrol commented on db/seeds.rb
>      password:              "swseuz2U",
Пароли **нельзя** хранить в открытом виде в репозитории, тем более публичном. (123456 не в счет)

2016-10-25 12:24 UTC, barmidrol approved these changes

2016-10-25 12:40 UTC, merged